### ISSUE TITLE
Gingerbread Compability

### ISSUE THREAD

**Issue by mrfanatic** [adrianchifor/Swiftnotes#10]
Hi, this is one of the cleanest, simple and easy to use note application app available. I want it to integrate on my existing app which uses Gingerbread API 9, will it work without using the search functionality?

**Comment by adrianchifor** [comment]
I will definitely look into that. There might be some more stuff that need to be changed to fully support 2.3.3+. It's not really a high priority right now because Gingerbread only accounts for ~7.4% of the current Android version distribution. Anyway, I will keep you updated!

**Comment by mrfanatic** [comment]
:+1:  Thanks for the reply. Sorry i can't labelled this post as 'question'.
