### ISSUE TITLE
Lock orientation?

### ISSUE THREAD

**Issue by vyp** [adrianchifor/Swiftnotes#11]
I know you added orientation functionality for #6, and I know you want to keep it simple, but I was wondering if you would add a way to 'lock' the orientation, and ignore any changes to it?

I would imagine something like a lock button, which when tapped, locks orientation, and when tapped again, unlocks it. Or perhaps more simply, respect the system "Screen rotation" option.. when the "Screen rotation" option is disabled, so is switching the orientation in the app.

My use case for this is when I have a device tilted enough so that the orientation changes to landscape, but I still want it in portrait mode.

**Comment by adrianchifor** [comment]
Will fix that now. Thanks!

**Comment by adrianchifor** [comment]
Fixed. Committed new changes and new APK. Update should be available on the PlayStore in a few hours.

**Comment by vyp** [comment]
Oh wow that was quick thanks so much. Will it be updated on f-droid too in a few hours (haven't checked yet)?

**Comment by adrianchifor** [comment]
Someone else put the app on F-Droid so I have no control over that. If you want the APK, you can download it here https://github.com/adrianchifor/Swiftnotes/blob/master/Swiftnotes_v303.apk?raw=true

**Comment by vyp** [comment]
Ouch, imo they should say they aren't the original author. Isn't it like a security concern (assuming the apks aren't signed)?. Anyway, thanks for letting us know, f-droid was how I originally installed it, hence why I asked.

**Comment by adrianchifor** [comment]
I've decompiled the Swiftnotes APK on F-Droid and it's the same as the official signed ones on PlayStore or on GitHub. People can sign/proguard their own APKs anyway using this project so it's not really to big of an issue I guess.

**Comment by vyp** [comment]
No worries, I don't anything about android development, but I think I'll just use your apks from now on. And thanks again, it was more like a feature request than a bug or something lol.

**Comment by adrianchifor** [comment]
From my perspective it was more like a bug because the orientation management didn't do what I wanted the first time, but now it's ok. Thanks for noticing and reporting it!

**Comment by vyp** [comment]
Ah I see then, didn't know that's what you wanted too. That's cool!
