### ISSUE TITLE
suggestion: use git tags

### ISSUE THREAD

**Issue by krt16s** [adrianchifor/Swiftnotes#13]
You might want to use `git tag $VERSIONNAME` (and `git push --tags`) on the commits that change vercodes. With $VERSIONNAME being either the Android versionname. This allows easier tracking (and building, since they are easier to read) of release versions and helps getting your app updated on f-droid, a free/libre/open souce app "store".

**Comment by adrianchifor** [comment]
Will do. I have a separate private repo for this app where I do all the dev, fixes, testing and experiments. I only commit major or bundled changes into this one to have a clean and linear progression. There are few a bits of code which I'm working on that I don't want to open-source just yet. But yea, will tag commits from now on. Thanks!

**Comment by krt16s** [comment]
Thanks, looking forward to it!
