### ISSUE TITLE
US English version

### ISSUE THREAD

**Issue by qopisbel** [adrianchifor/Swiftnotes#16]
I want to contribute the US english version. Would you kindly copy the values [strings.xml](https://github.com/adrianchifor/Swiftnotes/blob/master/app/src/main/res/values/strings.xml) file into a folder named "values-en-rUS" in the [res folder](https://github.com/adrianchifor/Swiftnotes/tree/master/app/src/main/res)? This will allow me to edit and create a PR using the GitHub web interface. It's only a couple words, favorite and color. Thanks

**Comment by adrianchifor** [comment]
Thanks for the help! Here's the link to the en-US resource: https://github.com/adrianchifor/Swiftnotes/blob/master/app/src/main/res/values-en-rUS/strings.xml

**Comment by qopisbel** [comment]
Done in #17
