### ISSUE TITLE
Suggestion: Option to switch order of notes (latest first)

### ISSUE THREAD

**Issue by vanitasvitae** [adrianchifor/Swiftnotes#20]
Hi!
I think it would be a nice feature when there is an option that lets the user change the order of the notes from ascending to descending and vice versa. So your latest notes appear at the beginning of the list.

Vanitas

**Comment by adrianchifor** [comment]
Already got this on the backlog. I'm halfway in on many improvements and new features, just need to find some time to get them done. Thanks anyway!

**Comment by vanitasvitae** [comment]
Okay nice :)
