### ISSUE TITLE
Allow empty titles

### ISSUE THREAD

**Issue by notfoss** [adrianchifor/Swiftnotes#24]
Hi, can you please make assigning a title optional? Thing is, when taking notes in a hurry, we are forced to provide a title, but since I am in a hurry, I end up giving useless titles like a, 1, etc.

So, it would be great if titles can be left empty.

**Comment by adrianchifor** [comment]
:+1:

**Comment by adrianchifor** [comment]
Added in release 3.1.4 1dac89b.
