### ISSUE TITLE
Only show the title

### ISSUE THREAD

**Issue by AndroidSceptic** [adrianchifor/Swiftnotes#26]
Hello Adrian,

firstly thank you for creating this small, simple and uncomplicated app, I was looking for, and for bringing it out as open source.

I've read that you still work and will do some improvements on it, maybe you also could implement one more feature. Having many notes it gets confusing, because every note is shown completely. It would be nice having the option(s) to reduce the view of all and maybe of certain notes permanently to see only the title. An option (a symbol) per note like the favorite-star to set it to "complete" or only to "title" would be great.

Furthermore you could think about implementing an opportunity to create categories the notes can be assigned to. Having many notes this could help keeping a good overview.
I think, this wouldn't disturb the smallness and simplicity of your wonderful app, that helps me with my notes.

Thank you in advance.

Best regards
Arthur

**Comment by adrianchifor** [comment]
Project no longer maintained unfortunately, will close the issue.
