### ISSUE TITLE
Where are notes stored?

### ISSUE THREAD

**Issue by RyanTG** [adrianchifor/Swiftnotes#27]
Hi, I made a mistake and did a factory reset on my device. I'm just wondering if I'm able to recover the notes I'd made (ideally, by locating them on the sdcard, since I'm not running android and can't reinstall the app). I have a folder \sdcard\Swiftnotes - but it's empty. In fact, it was empty before I did the reset. 

Great app, though! Thanks.

**Comment by adrianchifor** [comment]
The local notes would have been wiped if you did a factory reset. The backup notes are indeed stored in 'sdcard/Swiftnotes/backup.json' . If the Swiftnotes folder on the sdcard is empty, I think your local notes were not backed up. There's not much that can be done at this point I guess...you could enable automatic restore in Settings to hopefully restore the local notes, if you had backup app data enabled before the factory reset.

Really sorry about what happened and that I can't be of too much help. But good news, soon you will be able to backup your notes to the cloud so you will never lose them.

**Comment by RyanTG** [comment]
I appreciate the response!

Totally my fault for doing the factory reset. It was a moment of stupidity. I'd been switching back and forth between roms for weeks, and then had a lapse in judgment.

Also, perhaps this wasn't true:  "In fact, it was empty before I did the reset." Or I'd accidentally reset it way earlier.

Closing.
