### ISSUE TITLE
No text in dialogboxes when restoring notes from backup

### ISSUE THREAD

**Issue by vanitasvitae** [adrianchifor/Swiftnotes#28]
Hi
Whe I try to restore notes from backup, the dialogbox that opens has no text in it. There are only the two options "yes" and "no". Also if I press yes, the next infobox also has no text in it.

My language settings are german. Maybe there are missing strings?

**Comment by adrianchifor** [comment]
This happens on Android 6. Will issue a fix asap

**Comment by JasperWeiss** [comment]
Same goes for save changes dialogs

**Comment by gigan3rd** [comment]
Please have a look at [#30](https://github.com/adrianchifor/Swiftnotes/issues/30), it's fixed. Just waiting for a merge.

**Comment by adrianchifor** [comment]
Thanks a lot @gigan3rd for your work. Greatly appreciated. Sorry for the late response, been quite busy lately. Will try to do a merge this weekend and work a bit on the app.

**Comment by marmistrz** [comment]
@adrianchifor the problem still persists, #30 has not been merged yet.

**Comment by gigan3rd** [comment]
@marmistrz He seems to write this app from scratch now. This version can be considered obsolete. :)

**Comment by marmistrz** [comment]
@gigan3rd can you point me to the repo?

**Comment by adrianchifor** [comment]
Project no longer maintained unfortunately, will close the issue.

**Comment by adrianchifor** [comment]
Fixed in 3.1.4 release 1dac89b.
