### ISSUE TITLE
Removing hard coded strings 

### ISSUE THREAD

**Issue by hkasera** [adrianchifor/Swiftnotes#33]
In the `EditActivity.java`, I noticed that we have a lot of hard coded values everywhere. For eg. in [line number 48](https://github.com/adrianchifor/Swiftnotes/blob/master/app/src/main/java/com/moonpi/swiftnotes/EditActivity.java#L48), [line number 75](https://github.com/adrianchifor/Swiftnotes/blob/master/app/src/main/java/com/moonpi/swiftnotes/EditActivity.java#L75), [line number 187](https://github.com/adrianchifor/Swiftnotes/blob/master/app/src/main/java/com/moonpi/swiftnotes/EditActivity.java#L187).

These constants are default styling for the notes. Should we move them to a separate file so that they can be reused.

I would be happy to send a PR if this is a welcome request.

Thanks,
Harshita

**Comment by adrianchifor** [comment]
Project no longer maintained unfortunately, will close the issue.
