### ISSUE TITLE
Respect system orientation

### ISSUE THREAD

**Issue by nickjwhite** [adrianchifor/Swiftnotes#35]
I have "screen rotation" disabled in my android settings, but when editing a note this app doesn't respect that, so it rotates the screen if it detects that the orientation has changed. This was a surprise to me. I'm quite new to Android, but I expected that an app would not override my system settings.

It looks like the code doing this is setRequestedOrientation() in EditActivity.java. Would it make sense to just remove those lines and rely on users having the system rotate the screen if that's the option they've set, android-wide? It would to me, but then I expect you put that code there for a reason ;)

Thanks for the app, I use it daily and it is very handy indeed!

**Comment by adrianchifor** [comment]
Thanks for the feedback. I am currently working on a re-write of the app and will consider this issue. An update should be available pretty soon, if time allows.

**Comment by adrianchifor** [comment]
Project no longer maintained unfortunately, will close the issue.
