### ISSUE TITLE
Where to find swiftnotes data

### ISSUE THREAD

**Issue by Zeralda** [adrianchifor/Swiftnotes#39]
Hello,

I am not sure this is the right place to ask this question.
I had to perform a factory reset because of a bug on my phone. I was instructed to copy the folders from my Internal storage to my computer. I also made a backup with TWRP. After reinstalling Swiftnotes, I cannot find my notes anymore. Where are they stored? Is there a was to get them back without a swiftnotes backup?

Thanks a lot for your reply!

**Comment by adrianchifor** [comment]
Hi @Zeralda, the backup should be in external storage in a folder called Swiftnotes, so the full path should be something like `/storage/emulated/0/Swiftnotes/swiftnotes_backup.json` (the storage path might be different for your phone, maybe containing sdcard). After you have the `swiftnotes_backup.json` file restored, go in the app, press the 3 dots, 'Restore notes' and 'Yes'.

**Comment by Zeralda** [comment]
Hi Adrian,

Thanks a lot. I did not do a backup within Swiftnotes (I hadn't noticed that option), just a general backup of the whole phone. Does that explain why the Swiftnotes folder is empty?

Have a nice day!

**Comment by adrianchifor** [comment]
@Zeralda yes indeed, Swiftnotes does not automatically do backups.

**Comment by Zeralda** [comment]
Sorry to bother you again - I restored my data and made a backup but I will have to wipe the data again to get rid of the problem I had in the first place.

I can see my backup on my phone (with Amaze) but I can't see it on my computer (a Mac, I use Android File Transfer). Is sending the .json file to myself by e-mail a solution?

**Comment by Zeralda** [comment]
Me again... I rebooted the phone, now the backup is visible. Still have a lot to learn...
