### ISSUE TITLE
Messages don’t show up and Backup doesn’t work

### ISSUE THREAD

**Issue by MrJakmer** [adrianchifor/Swiftnotes#40]
Hello,

the messages don't work on my device (BQ Aquaris M5, API 23; see screenshot). I also tried a recent version of Android Studio (2.3.1) and with an emulator (Nexus 5X, API 25), which didn't help.

The backup functionality also doens’t work on my device with the version from the Google Play Store, but it is working if I build with Android Studio.

Greetings
MrJakmer

![swiftnotes_msg_screenshot](https://cloud.githubusercontent.com/assets/12643296/24954962/c8ebb52a-1f81-11e7-80d8-00dbf02f227f.png)

**Comment by adrianchifor** [comment]
Hi, I'm no longer actively maintaining Swiftnotes. I will however release a patch soon to fix the dialog issue. Backups seem to work fine on my phone (Pixel). If you can find why backups fail on your device, feel free to do a pull request :)
