### ISSUE TITLE
Copyright violation

### ISSUE THREAD

**Issue by Poussinou** [adrianchifor/Swiftnotes#43]
Hi @adrianchifor 

I found [this app ](https://play.google.com/store/apps/details?id=com.appwala.notes) on Google Play Store. This guys just took the source code, added some ads and put it on the Google Play Store...

As you are the owner of the source code, feel free to open a request to google [here](https://support.google.com/legal/contact/lr_dmca?product=googleplay) to remove the false app from the Store, if it's your wish ;)

Don't forget to tell Google that:

* The app is licensed under Apache License and this guy is violating it by distributing the app without warning this is Apache licensed;
* He is falsely claiming he made the app;
* Also tell them that this guy has done the same thing already with other apps. Probably this is worth mentioning. (I watch him)

**Comment by adrianchifor** [comment]
@Poussinou Good spot and thanks for the notice! I will get in touch with Google.

**Comment by adrianchifor** [comment]
Reported. Thanks again! Will close now.

**Comment by Poussinou** [comment]
Hi @adrianchifor 
[Here](https://play.google.com/store/apps/details?id=com.PaleVioletRed.notes) is another one. Plese report it.
All the apps of this [fake developper](https://play.google.com/store/apps/developer?id=Tuan+Nam+Team) are stolen open-source apps...

**Comment by adrianchifor** [comment]
Wow, that's a lot of stolen apps. Reported, thanks again!
