### ISSUE TITLE
Restore a backup without an SD card

### ISSUE THREAD

**Issue by Bugzey** [adrianchifor/Swiftnotes#45]
I am migrating to a new phone which supports extended storage via a MicroSD card, but I don't have one at the moment. When I try to restore my backup from my previous phone, the app insists that the backup must be stored in "External/Swiftnotes/swiftnotes_backup.json".

I copied the Jason file to the following directories to no avail:
/storage/emulated/0/Swiftnotes/swiftnotes_backup.json
/storage/emulated/0/swiftnotes_backup.json
/storage/emulated/0/External/swiftnotes_backup.json
/storage/emulated/0/External/Swiftnotes/swiftnotes_backup.json

Can anyone help with the matter?

**Comment by adrianchifor** [comment]
Hey, `/storage/emulated/0/` is external storage for devices that don't support MicroSD cards. For those that support MicroSD, most common external storage paths are `/storage/sdcard0/`, `/storage/sdcard1/`, `/storage/extSdCard/`, depends on the manufacturer. Therefore the correct path would be something like `/storage/sdcard0/Swiftnotes/swiftnotes_backup.json`.

On devices that don't have MicroSD, the correct path with be the first you mentioned `/storage/emulated/0/Swiftnotes/swiftnotes_backup.json`
