### ISSUE TITLE
Orientation is ignored

### ISSUE THREAD

**Issue by AlexVallat** [adrianchifor/Swiftnotes#6]
Ideally, landscape mode support would be appreciated, but even if it isn't, portrait mode should at least follow the screen orientation so the app doesn't appear upside down if you're holding your tablet a different way up.

**Comment by adrianchifor** [comment]
Noted. I will add that to the next update. Thanks!

**Comment by AlexVallat** [comment]
Nice one, thanks for the quick response! I was otherwise really happy to find Swiftnotes as a very fast no-nonsense app just to quickly jot down a bit of text, so if this is fixed it will be perfect for me.

**Comment by adrianchifor** [comment]
What do you think about user accounts with cloud sync on Android, iOS and Web?

**Comment by AlexVallat** [comment]
For me, personally, that's not something I would use at all. There are other heavier-weight note apps available that do syncing, but what I like about this one is its simplicity and speed.

If checking for sync updates meant that it was slower to start then I'd stick with an older version instead.

**Comment by adrianchifor** [comment]
Thanks for the feedback, really appreciate it!

**Comment by dalb8** [comment]
Eh, I have 3.1.3 insta!led (not sure if it was ApK in repo or gradled) but the app always opens in portrait; CM12.

**Comment by adrianchifor** [comment]
The notes list view will only be in portrait (either normal or reversed). The note view will rotate to all orientation types if rotation is unlocked.
